### ISSUE TITLE
Runtime upgrade to 0.9.12 (v23)

### ISSUE THREAD

**Issue by green-jay** [galacticcouncil/Basilisk-node#273] opened 2021-11-29 17:35 UTC
### Description
Basilisk's runtime needs to be upgraded from v19 -> v23 (0.9.10 -> 0.9.12) 
Collators are already running v0.9.12 so no need to upgrade them.

### Actual status
Currently runtime upgrade is not executing properly.

Tested current version of master upgrading to a new build with bumped version.

After using
![image](https://user-images.githubusercontent.com/75261756/143915141-22d2cfdb-0026-4d0f-b3dd-5437fe2e9a83.png)

using different WASMs produced different errors.

Uncompressed + Compact WASM:
![image](https://user-images.githubusercontent.com/75261756/143914246-02f557b9-606a-46b6-8177-b59f3bfc3334.png)

stalling chain afterwards.

Compressed WASM:
Sudo event: OK, but the chain is stalling afterwards

Using SetCodeWithoutChecks produces same results.

### Expected status
Runtime upgrade is tested successfully on local chain and a testnet before the actual upgrade.

**Comment by lumir-mrkva** [comment] 2021-11-30 03:07
@green-jay the only difference in the new runtime that you're upgrading is the spec version dump?

**Comment by green-jay** [comment] 2021-11-30 07:34
> 

yes, I only bumped spec and cargo version. once 0.9.12 -> 0.9.12 is ok, it would be good to test 0.9.10 -> 0.9.12 because some people reported problems with direct upgrade and had to go incrementally 0.9.10->0.9.11->0.9.12

**Comment by lumir-mrkva** [comment] 2021-12-04 18:59
caused by the polkadot 0.9.12 relay chain, fixed in 0.9.13

**Closed by lumir-mrkva** 2021-12-04 18:59 UTC
